apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: product
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: product-config
          image: 492804330065.dkr.ecr.us-east-2.amazonaws.com/go-coffeeshop-product
          name: product
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
