version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:

      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    healthcheck:
      test: ["CMD", "pg_isready"]
    ports:
      - "5432:5432"