# rabbitmq-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q= # base64 encoded 'guest'
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # base64 encoded 'guest'